### PR TITLE
Speedup duplicate rule detection

### PR DESCRIPTION
**Pull request by Antiarchitect**
It seems I've simplified and speed up `duplicate_rule?` function. May be related to https://github.com/puppetlabs/puppetlabs-firewall/issues/1053

### CODE REVIEW

**Comment by Antiarchitect** [comment]
Will test it in a day or two - we're facing the same issue when number of rules are hundreds

**Comment by Antiarchitect** [comment]
We've tested `duplicate_rule?` and it is called on every `exists?` just to throw some warnings for each rule. So the complexity is O(n^2). We have about 3000 rules on the machine and whole process tooks very long. For the test I just replaced `duplicate_rule?` with

```
def duplicate_rule?(rule)
    false
end
```
 and it gets back to normal. Please do something. It seems we need global hash with O(1) check of a duplicate.

**Comment by chelnak** [comment]
@Antiarchitect We appreciate you going in to such detail with this.

From memory this was a trick one.. due to the requirements around the change O(1) may be hard to achieve.. but i'm certain we can make it faster!

I'll bring it up with the team and get some eyes on it.

**Comment by stefanlasiewski** [comment]
Thanks for looking @chelnak. This is an important fix for us as well.

**Comment by LukasAud** [comment]
Hi @Antiarchitect, sorry for the long delay in feedback. In order to keep better track of this issue and avoid our PR page cluttering, we would like for this topic to be moved into our "Issues" page and, if possible, linked onto our current ongoing discussion about the [Firewall module re-architecture project](https://github.com/puppetlabs/puppetlabs-firewall/issues/1100).

**Comment by LukasAud** [comment]
Closing stale PR. Recommended action has already been stated above.

**Pull request closed without merging**
