### PR TITLE
Added support for setting the MSS of a packet.

### PR DESCRIPTION
**Pull request by jpds**
Add support for matching and setting a new TCP MSS value.

This resolves https://tickets.puppetlabs.com/browse/MODULES-1500 .

### CODE REVIEW

**Comment by cmclaughlin** [comment]
I was just looking for this functionality and found this.  Looks good to me.  Will this be merged soon?

**Comment by jonnytpuppet** [comment]
Hi There

Thank you for your submission.
Unfortunately, your tests fail on CentOS 5. As this is a supported OS for this module, it would be great if you could re-test and push any further fixes needed in order for this to be merged.

Thanks!

**Comment by jonnytpuppet** [comment]
@jpds ping, is there any update on this?

**Comment by jpds** [comment]
This branch should be good to go now.

**Comment by jonnytpuppet** [comment]
Hi There

Your tests still fail.

I tested your acceptance test against Debian 7 and CentOS 5 and they both failed. Please submit commits that address this issue.

Thanks!

**Comment by jonnytpuppet** [comment]
Also, please remember to squash your commits

**Comment by jpds** [comment]
Can you show me how to run the acceptance tests? All I see is the green tick here. :)

**Comment by dalen** [comment]
Also need this feature.

The way to run the acceptance tests is as far as I know to install vagrant, virtualbox and bundler. Run `bundle install` then `bundle exec rake beaker`.

**Comment by dalen** [comment]
Also, run `bundle exec rake beaker_nodes` to get a list of nodesets, and `BEAKER_set=setname bundle exec rake beaker` to run the tests on that set. By default it only runs on centos-64-x64.

**Comment by dalen** [comment]
Did a fix of the acceptance test and pushed in a new PR (needed to set tcp_flags to SYN,RST SYN)

**Comment by jonnytpuppet** [comment]
Closing due to #524 which bring in these changes with some other fixes.

**Pull request closed without merging**
