### PR TITLE
(MODULES-3514) Also purge fw rules added during catalog apply

### PR DESCRIPTION
**Pull request by jaakkosipari**
See https://tickets.puppetlabs.com/browse/MODULES-3514

### CODE REVIEW

**Comment by jsi-p** [comment]
I don't quite understand the UTF-8 error from the build with Travis. The same lint check "works on my machine".

**Comment by bmjen** [comment]
Thanks @jaakkosipari , we're going to have to investigate whether this change will have any unwanted ramifications due to changing the ordering of the code execution from generate to eval_generate

**Comment by jaakkosipari** [comment]
@bmjen I just noticed the change might introduce warnings like this: 'Warning: OUTPUT:filter:IPv4: appears to have a negative number of dependencies'.

I'll try to find out the cause, but it's possible my understanding of Puppet internals and the Firewall module isn't enough to figure out the problem. To reproduce, one probably needs two modules one declaring firewallchain resources and the other (or both) declaring firewall resources for the equivalent chains (eg. INPUT or OUTPUT). It's not necessary to have 'purge => true' for the firewallchain resources to see warnings (while it does give out more 'negative number of dependencies' warnings with purge => true).

Sorry to not have noticed this earlier.

**Comment by bmjen** [comment]
Sounds good! Thanks @jaakkosipari !

**Comment by jaakkosipari** [comment]
I tried to investigate the 'negative number of dependencies'-problem. It seems generate and eval_generate don't just differ on when they're called, but also how the returned data (new resources) is processed and added to the resource graph by Puppet.

Unfortunately I don't have enough time to resolve this issue.

We are just going to resolve our original issue (firewall rules added during puppet run not purged) by using two consecutive puppet runs.

**Comment by tphoney** [comment]
Hi @jaakkosipari , thanks for the work you have put into this pull request. However due to inactivity and needing rebased this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

**Pull request closed without merging**
