### PR TITLE
(MODULES-5340) Understand negated match sets

### PR DESCRIPTION
**Pull request by nbarrientos**
This patch allows the provider to understand rules that contain negated
match sets when parsing the ruleset.

### CODE REVIEW

**Comment by eputnam** [comment]
thanks @nbarrientos !

**Comment by nbarrientos** [comment]
Sure. Watch this space :)

**Comment by nbarrientos** [comment]
@eputnam there you go! 😃

**Comment by nbarrientos** [comment]
The test does not pass on master:

```
  1) iptables provider when converting rules to resources for test data 'ipset_negated' the parameter 'chain' should match "PREROUTING"
     Failure/Error: expect(resource[param_name]).to eq(data[:params][param_name])
     
       expected: "PREROUTING"
            got: "tcp"
     
       (compared using ==)
     # ./spec/unit/puppet/provider/iptables_spec.rb:232:in `block (6 levels) in <top (required)>'

  2) iptables provider when converting rules to resources for test data 'ipset_negated' the parameter 'proto' should match "tcp"
     Failure/Error: expect(resource[param_name]).to eq(data[:params][param_name])
     
       expected: "tcp"
            got: "1094"
     
       (compared using ==)
     # ./spec/unit/puppet/provider/iptables_spec.rb:232:in `block (6 levels) in <top (required)>'

  3) iptables provider when converting rules to resources for test data 'ipset_negated' the parameter 'dport' should match ["1094"]
     Failure/Error: expect(resource[param_name]).to eq(data[:params][param_name])
     
       expected: ["1094"]
            got: ["060 ipset"]
     
       (compared using ==)
     # ./spec/unit/puppet/provider/iptables_spec.rb:232:in `block (6 levels) in <top (required)>'

  4) iptables provider when converting rules to resources for test data 'ipset_negated' the parameter 'state' should match ["NEW"]
     Failure/Error: expect(resource[param_name]).to eq(data[:params][param_name])
     
       expected: ["NEW"]
            got: ["! setname1"]
     
       (compared using ==)
     # ./spec/unit/puppet/provider/iptables_spec.rb:232:in `block (6 levels) in <top (required)>'

  5) iptables provider when converting rules to resources for test data 'ipset_negated' the parameter 'ipset' should match ["! setname1 src"]
     Failure/Error: expect(resource[param_name]).to eq(data[:params][param_name])
     
       expected: ["! setname1 src"]
            got: ["src"]
     
       (compared using ==)
     # ./spec/unit/puppet/provider/iptables_spec.rb:232:in `block (6 levels) in <top (required)>'
```
So we should be good to go now.

**Comment by nbarrientos** [comment]
Ping @eputnam

**Comment by eputnam** [comment]
@nbarrientos looks like unit tests are passing again?

**Pull request merged**
