### PR TITLE
MODULES-10693: Add Hmark support (Draft, help wanted)

### PR DESCRIPTION
**Pull request by fetzerms**
Hi,

this is a first draft/attempt to add support for the HMARK iptables extension, as requested in MODULES-10693.

Can somebody help me how to properly define the order of resources in ```@resource_list```? After this, I can add proper testing cases and remove the draft flag.

Thank you!

### CODE REVIEW

**Comment by fetzerms** [comment]
@david22swan do you maybe have some good pointers on how to find out the order of @resource_list in iptables? I think that is the last part that is missing.

**Comment by fetzerms** [comment]
@adrianiurca @sheenaajay - is there any chance to get some assistance? It works, but I am just unsure about `@resource_list`.

**Comment by adrianiurca** [comment]
Hey @fetzerms, sorry we didn't take action on this PR. Looking forward to providing a solution as soon as possible, probably this week. Apologize for the late response.

kind regards,
@adrianiurca

**Comment by fetzerms** [comment]
@adrianiurca @david22swan @sheenaajay : Sorry for nagging too much. Is there anybody who could help with determining the oder of ````@resource_list ```` in ip(6)tables.rb? If yes, this PR could be merged pretty soon (and I can stop using my own fork :-))

**Pull request closed without merging**
