### PR TITLE
(MODULES-10113) add option to ignore chains

### PR DESCRIPTION
**Pull request by atarax**

### CODE REVIEW

**Comment by sheenaajay** [comment]
Thanks @atarax for submitting the PR. Could you please fix the rubocop error. Thank you.

**Comment by atarax** [comment]
@sheenaajay this is currently a work-in-progress, i hope i will find time to work on this soon

**Comment by michaeltlombardi** [comment]
Hi, @atarax, it looks like this pull request hasn't seen any activity in about 90 days. Is this something that you're still able to work on? We're happy to keep this pull request open if there's forward movement, and we'll leave it open for another two weeks from now. If there isn't any activity by then we may have to close this pull request due to lack of activity.

Closing the pull request wouldn't mean we don't consider this change valuable. However we try to keep all open pull requests moving towards completion, and closing stale pull requests help us focus on more active pull requests.

If you have any questions or concerns, please don't hesitate to ping us in the Slack channel on slack.puppet.com.

**Comment by sheenaajay** [comment]
@atarax Thanks for submitting the PR. Since there hasn't seen any activity for a while we are going to go ahead and close this pull request for the time being. Please feel free to re-open this pull request at any time. Thank you.

**Pull request closed without merging**
