### PR TITLE
Add support for NFLOG options to ip6tables

### PR DESCRIPTION
**Pull request by frh**

### CODE REVIEW

**Comment by sheenaajay** [comment]
Thank you @frh for submitting the PR. Could you please add unit tests to verify the changes. This is a sample pr https://github.com/puppetlabs/puppetlabs-firewall/pull/917/files#diff-c4e9ab14ac1cfe5af5148d4ae962a10a . Thanks again

**Comment by frh** [comment]
> Thank you @frh for submitting the PR. Could you please add unit tests to verify the changes. This is a sample pr https://github.com/puppetlabs/puppetlabs-firewall/pull/917/files#diff-c4e9ab14ac1cfe5af5148d4ae962a10a . Thanks again

Thanks for the review. Is it okay with this newest commit?

**Comment by frh** [comment]
@sheenaajay Have you had a chance to look over the unit tests I added? Let me know if you'd want any changes to them.

**Comment by sheenaajay** [comment]
@frh Thanks for incorporating the comments. Much appreciated for your contribution. Taking a look now.

**Pull request merged**
