### PR TITLE
Prevent sources with zero prefix length being applied every agent run

### PR DESCRIPTION
**Pull request by nabertrand**
## Summary
Prevent `source` and `destination` values with a prefix length of zero causing the Puppet agent to attempt corrections on every run

## Additional Context
See #1188 

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

### CODE REVIEW

**Comment by praj1001** [comment]
@nabertrand , Can u please fix the specs ??

**Comment by trevorrea** [comment]
@praj1001 Can you not just fix it? It's literally removing a space from:-

! [:source, :destination].include?(property_name)

to

![:source, :destination].include?(property_name)

**Comment by EnigmaticCypher** [comment]
@malikparvez can this be approved & merged please? Or do I need to force the issue by getting a ticket raised to perforce under an enterprise support contract? The community provided a fix for this almost a full year ago and multiple issues in this repository have been raised about it.

**Review by praj1001 — APPROVED** [review]

**Comment by praj1001** [comment]
@nabertrand @trevorrea @EnigmaticCypher, Approved & Merged.

**Comment by trevorrea** [comment]
@praj1001 can we also get a release pushed to Puppet Forge please?

**Comment by sahaqaa** [comment]
When approx it (new version of module, which includes this fix) will be released to Puppet Forge?

**Pull request merged**
