### PR TITLE
MODULES-1832 - add Gentoo support

### PR DESCRIPTION
**Pull request by derdanne**
Add Gentoo support

### CODE REVIEW

**Comment by tphoney** [comment]
Thanks for the contribution. Could you please squash your commits, and maybe update the readme as well.

**Comment by derdanne** [comment]
Hi @tphoney, i squashed my commits and updated metadata.json.

Could you please specify what to update in readme? I couldn't find any distribution specific part.

**Comment by tphoney** [comment]
I was wondering if there were any OS specific limitations, like there is for SLES.
Sorry i was not very clear.

**Comment by derdanne** [comment]
Hi @tphoney,

i did not discover any limitation factors on Gentoo systems so far. The module works for me with the committed changes like it is documented in the readme on many production systems.

**Comment by tphoney** [comment]
Thanks @derdanne

**Pull request merged**
