### PR TITLE
allow iptables package to be updated

### PR DESCRIPTION
**Pull request by cristifalcas**
Add a new parameter in order to allow the iptables package to be updated

### CODE REVIEW

**Comment by bmjen** [comment]
Thanks @cristifalcas! This looks like a good addition. Can you please squash the two commits into one?

**Comment by mentat** [comment]
Hi again @cristifalcas, would you mind squashing this down?

**Comment by cristifalcas** [comment]
sorry for the delay

**Comment by tphoney** [comment]
@cristifalcas  Thanks for the work that you have put in, there are a number tests failing, could you please have a look.

**Comment by cristifalcas** [comment]
Fixed

**Comment by tphoney** [comment]
Thanks, can you please squash. the code looks good to me.

**Comment by cristifalcas** [comment]
I have no idea how to remove the "Merge remote-tracking branch" commit. Is it ok if I close this PR and open a new one?

**Comment by tphoney** [comment]
if you are on the CLI:
git rebase --interactive HEAD~2

it will look something like 

pick 690cb20 Adding bug workaround in tests for Debian 8
pick 750948e Enabled usage of the $ntpsigndsocket parameter, for socket signing when needed.

change it to 

pick 690cb20 Adding bug workaround in tests for Debian 8
s 750948e Enabled usage of the $ntpsigndsocket parameter, for socket signing when needed.

This will squash that commit. 

Then re-push again

**Comment by tphoney** [comment]
or https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by tphoney** [comment]
or create a new pr :+1:

**Comment by cristifalcas** [comment]
done

**Comment by tphoney** [comment]
great work !!!

**Pull request merged**
