### PR TITLE
Fix PR#492 acceptance test, ability to set MSS of TCP SYN packets

### PR DESCRIPTION
**Pull request by dalen**

### CODE REVIEW

**Comment by dalen** [comment]
This is a rebase squash of PR#492 with a fix to the acceptance tests.

**Comment by bmjen** [comment]
@dalen Thanks for getting this PR rebased and squashed! But acceptance tests still fail on centos-5.

**Comment by jonnytpuppet** [comment]
@dalen thanks for the work. I'll pull down your branch and do a few fixes to remove CentOS5 from the testing.

**Comment by jonnytpuppet** [comment]
Closing due to #524 which takes in these changes with a few simple fixes.

**Pull request closed without merging**
