### PR TITLE
support for multiple ipsets in a rule

### PR DESCRIPTION
**Pull request by nabam**
Support for multiple ipsets in a single rule. This feature is very handy
if you need to match source and destination from different ipsets.
Iptables arguments are a bit wierd, but it works, details are in
https://utcc.utoronto.ca/~cks/space/blog/linux/IptablesIpsetsMultipleMatches

### CODE REVIEW

**Comment by bmjen** [comment]
This looks ok to me. Can @jonnytpuppet take a look at this to double check the formatting?

**Comment by tphoney** [comment]
@jonnytpuppet ping

**Comment by daenney** [comment]
Ping @hunner

**Comment by HelenCampbell** [comment]
Hey @nabam , thank you for contributing! Sorry about the lack of review so far, I'm pushing to get this PR seen to in our next community meeting on Thursday. Thank you for your patience.

**Comment by jonnytpuppet** [comment]
@nabam Thank you so much for your contributions!

It would be appreciated if you could do a README update to state that multiple values can be passed in.

Also, I'd love to see an acceptance test using multiple values, just to prove that this continues to work on multiple platforms.

Thanks!

**Comment by nabam** [comment]
@jonnytpuppet isn't it already done?

**Comment by daenney** [comment]
@jonnytpuppet Looking at the code all the concerns you've mentioned are already addressed in the original PR. There's a small patch to the README mentioning it can take a string or array and there's an acceptance test that has multiple values.

**Pull request merged**
