### PR TITLE
Add --notrack flag

### PR DESCRIPTION
**Pull request by jbro**
Added a `notrack` option to the firewall resource to set `--notrack` on the iptables command line.

### CODE REVIEW

**Comment by daianamezdrea** [comment]
Hi @jbro , thank you for your contribution ! Here Travis is failing because of Rubocop offenses:
`38 files inspected, 1 offense detected
RuboCop failed!`
Can you repair this ? Let me know if you need help

**Comment by carabasdaniel** [comment]
Hi @jbro,

This feature looks good, but adding a few tests will ensure this works as intended.

**Comment by jbro** [comment]
Hi @carabasdaniel 

I wouldn't know where to start adding tests or what sort of tests to create, can you give me a hint?

**Comment by carabasdaniel** [comment]
Hi @jbro,

For unit testing you can follow similar tests as the ones found in the [iptables_spec](https://github.com/puppetlabs/puppetlabs-firewall/blob/master/spec/unit/puppet/provider/iptables_spec.rb).

For acceptance tests you can try adding a test in [the standard usage spec](https://github.com/puppetlabs/puppetlabs-firewall/blob/master/spec/acceptance/standard_usage_spec.rb).

**Comment by jbro** [comment]
So I've had a look a look, and I can easily enough add something like:

    diff --git a/spec/acceptance/standard_usage_spec.rb b/spec/acceptance/standard_usage_spec.rb
    index bcf8197..96e1560 100644
    --- a/spec/acceptance/standard_usage_spec.rb
    +++ b/spec/acceptance/standard_usage_spec.rb
    @@ -27,6 +27,14 @@ describe 'standard usage tests' do
               proto   => 'all',
               ctstate => ['RELATED', 'ESTABLISHED'],
               action  => 'accept',
    +        }->
    +        firewall { '004 do not track UDP connections to port 53':
    +          chain => 'PREROUTING',
    +          table => 'raw',
    +          proto  => 'udp',
    +          dport => 53,
    +          jump => 'CT',
    +          notrack => true,
             }
           }
           class my_fw::post {

But to be frank I don't plan on spending time setting up the necessary test rig or trying to understand how to tie into the unit tests for such a small patch as this.

**Comment by adrianiurca** [comment]
Thank you @jbro for your contribution. I submitted a new PR which adds a new acceptance test for the notrack parameter. I mention that your contribution in referenced in this new PR(#931). After the PR #931 is merged your PR will be closed.

Kind regards,
@adrianiurca

**Pull request closed without merging**
