### PR TITLE
(MODULES-6876) lib/puppet/provider/firewall/iptables.rb - comments cleanup for parsing

### PR DESCRIPTION
**Pull request by tskirvin**
Per <https://tickets.puppetlabs.com/browse/MODULES-6876>, there are problems with parsing some iptables rules with space and quotes (specifically ones created by podman).  This re-clears the comments field if it made it through earlier parsing.  (This probably isn't the only or best way to solve this problem, but we need to proceed).

### CODE REVIEW

**Comment by tskirvin** [comment]
FYI, it looks like the CI failed due to an inability to reach github.com, so I don't know what that's about...

**Comment by tskirvin** [comment]
Working with my internal licensing folks.

**Comment by tskirvin** [comment]
Licensing folks have approved, reopening.

**Comment by daianamezdrea** [comment]
Hi, I tried to rebase your PR in order to merge it but it seems I don't have permissions, do you mind to rebase it ? Thank you

**Comment by tskirvin** [comment]
I think the rebasing is done, please confirm?  (The workflows are currently awaiting approval.)

**Comment by tskirvin** [comment]
The failed checks with Rocky Linux appear to be with the Rocky Linux image, not necessarily my code?

**Comment by daianamezdrea** [comment]
Yes, indeed, the failure is not related with your PR, thank you for your contribution!

**Pull request merged**
